### ISSUE TITLE
Trying to randomize an empty Enum fails with an IllegalArgumentException

### ISSUE THREAD

**Issue by LeJeanbono** [j-easy/easy-random#393]
Hi,
I have to randomize an object with an empty enum :
```java
public enum MyEnum {
}
```
Can we consider `getRandomValue` of `EnumRandomizer` return `null` if `enumConstants.size()` equal zero?

Actually it throw 
```
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at org.jeasy.random.randomizers.misc.EnumRandomizer.getRandomValue(EnumRandomizer.java:120)
	at org.jeasy.random.EasyRandom.randomize(EasyRandom.java:179)
```
Can make a PR.

**Comment by benas** [comment]
Good catch, even though I don't see the added value of an empty enum. But still, Easy Random should not crash with an IAE.

> Can make a PR.

You are welcome!
