### ISSUE TITLE
Number-based validation annotations are not supported well on primitive wrapper

### ISSUE THREAD

**Issue by dadiyang** [j-easy/easy-random#420]
Suppose we have these Long field annotated with Postive/PositiveOrZero/Negative/NegativeOrZero: 
![image](https://user-images.githubusercontent.com/28141217/83958264-4f7d4700-a8a2-11ea-957a-23c37be8fc88.png)

EasyRandom will occur an exception, because it tries to set a Long field with int value.

![image](https://user-images.githubusercontent.com/28141217/83958119-b7329280-a8a0-11ea-8b4e-27f0c00689d8.png)

**Comment by onacit** [comment]
I'm facing the very same problem.
EasyRandom seems trying to set primitive values to those wrapper types.

**Comment by dadiyang** [comment]
It's a general problem. And I fix it on my pull request. Hope @benas fix this problem as quickly as possible. Thanks!

**Comment by lancedfr** [comment]
I have the same issue when using

`  @Positive
  private BigInteger number;
`

> org.jeasy.random.ObjectCreationException: Unable to create a random instance of type class com.SupplierTransaction
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jeasy.random.util.ReflectionUtils.setProperty(ReflectionUtils.java:136)
	at org.jeasy.random.FieldPopulator.populateField(FieldPopulator.java:93)
	at org.jeasy.random.EasyRandom.populateField(EasyRandom.java:206)
	at org.jeasy.random.EasyRandom.populateFields(EasyRandom.java:195)
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:162)
	... 65 more

When investigating this in my case it seems like
org.jeasy.random.RegistriesRandomizerProvider#getRandomizer method is returning IntegerRangeRandomizer and not BigIntegerRandomizer causing the argument type mismatch

**Comment by lancedfr** [comment]
> It's a general problem. And I fix it on my pull request. Hope @benas fix this problem as quickly as possible. Thanks!

Thanks for fixing it. I was about to look into a fix myself. well done
