### ISSUE TITLE
Not able to generate random object when the class is a composition of a field of type 'java.lang.CharSequence'

### ISSUE THREAD

**Issue by rajeshhereforyou** [j-easy/easy-random#456]
Thank you for taking time to open this issue! Please check the [known limitations](https://github.com/j-easy/easy-random/wiki/known-limitations) section before opening an issue.

Please provide as much context as possible to help us fixing the issue (at least easy-random version you are using).

* If you are reporting a bug, the best way is to provide a failing test.
* If you are requesting a feature, don't hesitate to explain in detail your suggestion with code examples.
* If you have a question, please first check if there is no (closed) issue about it. You may ask your question on the [Gitter channel](https://gitter.im/j-easy/easy-random) of the project.

Many thanks upfront!

**Comment by rajeshhereforyou** [comment]
Here is my object - 

Public class MyClass {

public List<Identifier> ids;
public String name;


}

public class Identifier{

public java.lang.CharSequence value;

}

and I'm using the below gradle dependency

group: 'io.github.benas', name: 'random-beans', version: '3.7.0'

and here is the error i'm getting -

Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to create type: java.lang.CharSequence for field: value of class: Identifier
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:85)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:158)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:149)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:120)
	... 66 more
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type interface java.lang.CharSequence
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:124)
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:122)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:81)
	... 69 more
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to create an instance of type: interface java.lang.CharSequence
	at io.github.benas.randombeans.ObjectFactory.createInstance(ObjectFactory.java:66)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:109)
	... 71 more
Caused by: java.lang.InstantiationError: java.lang.CharSequence
	at sun.reflect.GeneratedSerializationConstructorAccessor29.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at io.github.benas.randombeans.ObjectFactory.createNewInstance(ObjectFactory.java:79)
	at io.github.benas.randombeans.ObjectFactory.createInstance(ObjectFactory.java:64)
	... 72 more

**Comment by benas** [comment]
Thank you for opening this issue. Please note that random-beans v3.7.0 is not maintained anymore. I encourage you to upgrade your code to the latest Easy Random version.

Now regarding the issue, `java.lang.CharSequence` is an interface, that's why ER is not able to generate a random instance of it. You can activate the [scanClasspathForConcreteTypes](https://github.com/j-easy/easy-random/wiki/Randomization-parameters#classpath-scanning) parameter and ER will try to find a concrete type from the classpath (note that this might still fail if ER is unable to randomize the concrete type it finds). Otherwise, you need to register a custom randomizer for that field.
