### ISSUE TITLE
List field with @Size annotation does not work with bean validation.

### ISSUE THREAD

**Issue by nielinjie** [j-easy/easy-random#504]
Hi all - 

Here is my code.
When I have a List field (In Book class), with a @Size annotation. If @Size removed, code works fine.
Please help.

```kotlin
repositories {
	mavenCentral()
	maven {
		url("https://oss.sonatype.org/content/repositories/snapshots")
	}
}

dependencies {
	//.....
	testImplementation 'org.jeasy:easy-random-core:6.0.0-SNAPSHOT'
	testImplementation 'org.jeasy:easy-random-bean-validation:6.0.0-SNAPSHOT'
```

``` java

import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import lombok.Data;
import org.jeasy.random.EasyRandom;
import org.jeasy.random.EasyRandomParameters;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.notNullValue;

public class RandomBugTest {
    EasyRandomParameters parameter = new EasyRandomParameters().seed(238L);
    @Data
    class Book{
        @Size(min=0) //works if this line removed.
        @NotNull
        @Valid
        private List<Dog> dogs;
    }
    @Data
    class Dog{
        @NotNull
        private String name;
        @Min(0)
        private int age;
    }
    @Test
    public void test() {
        Book a = new EasyRandom(parameter).nextObject(Book.class);
        assertThat(a.getDogs(), notNullValue());
        a.getDogs().forEach(p -> {
            assertThat(p.getAge(), greaterThanOrEqualTo(0));
        });
    }
}
```
Error log reads - 
```
org.jeasy.random.ObjectCreationException: Unable to create a random instance of type class com.zywkeji.demo.RandomBugTest$Book
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:191)
	at org.jeasy.random.EasyRandom.nextObject(EasyRandom.java:103)
	at com.zywkeji.demo.RandomBugTest.test(RandomBugTest.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 

.......
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.jeasy.random.RegistriesRandomizerProvider.getRandomizer(RegistriesRandomizerProvider.java:66)
	at org.jeasy.random.RegistriesRandomizerProvider.getRandomizerByField(RegistriesRandomizerProvider.java:47)
	at org.jeasy.random.FieldPopulator.getRandomizer(FieldPopulator.java:118)
	at org.jeasy.random.FieldPopulator.populateField(FieldPopulator.java:79)
	at org.jeasy.random.EasyRandom.populateField(EasyRandom.java:228)
	at org.jeasy.random.EasyRandom.populateFields(EasyRandom.java:217)
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:184)
	at org.jeasy.random.EasyRandom.nextObject(EasyRandom.java:103)
	
```

**Comment by nielinjie** [comment]
I did  a rush check on source code ,and got this solved. 
Change this line to following code  - 
https://github.com/j-easy/easy-random/blob/fc58f6129b385b7541a12235511cf5c0a6bc4eec/easy-random-core/src/main/java/org/jeasy/random/RegistriesRandomizerProvider.java#L61

Just FYI, I did not do complete test, for example performance check.

```java
private Randomizer<?> getRandomizer(final Provider provider) {
        return new ArrayList<>(registries).stream()  //change following line to this.
//        return registries.stream() 
                .map(provider::getRandomizer)
                .filter(Objects::nonNull)
                .sorted(priorityComparator)
                .findFirst().orElse(null);
    }
```

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. You are using the snapshots of v6, in which bean validation support will be discontinued, see #499 .

Please check https://github.com/j-easy/easy-random/issues/499#issue-1805982823 on how to proceed, or register a custom randomizer for that field.
